services:
  app:
    build: .
    container_name: parsing_app
    cpu_shares: 2048 # устанавливаем приоритет повыше
    deploy:
      resources:
        limits:
          memory: 1GB  # Ограничиваем до 2 ГБ          
        reservations:
          memory: 0.8GB  # Минимальный гарантированный объем памяти
    command: ["uv","run", "main.py"]